### ISSUE TITLE
Gnome 45 compatibility

### ISSUE THREAD

**Issue by dieub56** [zagortenay333/timepp#242]
Please allow gnome 45 users to benefit from this great tool !

**Comment by Crian69** [comment]
+1

**Comment by Tonziro** [comment]
+1)

**Comment by jasiralavibiztripz** [comment]
+1
Thanks for the great extension, i was really enjoying it. Pls update.

**Comment by mix-7** [comment]
+1
Thanks for the this extension. 
Please   update.

**Comment by Tonziro** [comment]
Is there any chance, that cronomix extension will get gnome 45 support till 2024?

**Comment by wada3n** [comment]
++

**Comment by MTalhaofc** [comment]
Waiting for 45.2 shell version :) :+1:

**Comment by altsalt** [comment]
In case there are folks wondering about the 👎🏼 reactions, they likely due to +1/still waiting/etc messages just creating noise. The same thing can be accomplished by adding a 👍🏼 reaction to the first post.

After a cursory review, it appears that the main work that needs to be done is to cover the CJS to ESM (e.g., `const {var} = require('./util')` => `import {var} from './util'`).

Unsure whether there is an easy way to do this work collaboratively as it is mostly simple, but tedious. If someone steps up to do an initial pass of, say the example above, then they could open a draft PR and maybe someone else could take another pass at a different change.

Anyway, we are all anxious to have this extension work again and I hope that @zagortenay333 can weigh in. Or if they have moved on, I hope that someone else will step up, create a fork with maintenance plan, and propose taking the extension over.

**Comment by zagortenay333** [comment]
I'll look into it next week. Should be pretty simple.

**Comment by MTalhaofc** [comment]
Don't forget to make an issue aswell. so we can easily be notified :0

**Comment by zagortenay333** [comment]
In short, fuck the entire gnome-shell project.

I have made a bunch of fixes including the file paths bullshit, but I don't want to deal with this shit anymore.

If any of you want to contribute there is the `g45` branch. You'll need to fix the fact that in g45 one can no longer invoke the gettext functions from global scope apparently. Also the invocation lookupByUUID is broken for some reason.

**Comment by altsalt** [comment]
Thank you for your efforts thus far @zagortenay333 it will be a big help. When doing a review, it looked like many tedious changes and I really hope Gnome stops making these huge breaking steps. At the very least they should start following [semantic versioning](https://semver.org/).

**Comment by zagortenay333** [comment]
@altsalt I think the only thing left to do is this gettext/lookupByUUID thing. There are a lot 
of instances of me invoking the _() function in what is essentially an enum that is defined in file scope, and that is apparently not possible anymore:

https://github.com/zagortenay333/cronomix/blob/master/src/utils/markup/renderer.ts#L530

They also seem to have deprecated the get_vbar_scroll* functions.

**Comment by dieub56** [comment]
Will no one step up to revive this extension ? Most of us would really like to keep using it but don't have the skills to make the few necessary changes needed to get it working with Gnome 45... My understanding is it would work with Gnome 46 as well and for as long as the Gnome devs don't make any other extension breaking changes, which could be a while.

**Comment by altsalt** [comment]
It's on a todo for me, but pretty far down, would definitely love to see someone else take it on if able.

**Comment by zagortenay333** [comment]
Ok, I finally calmed down :) and fixed most the issues I described above.

There are still more bugs to be fixed before I release it.

**Comment by zagortenay333** [comment]
It's done.

**Comment by zagortenay333** [comment]
Oops. Hold on I made a mistake when git squashing...

**Comment by altsalt** [comment]
Thank you so much @zagortenay333 !
